package com.hardcraft.world;
import java.nio.file.*;import java.sql.*;import java.util.*;
final class ClaimRepository{
 private final String url;ClaimRepository(Path p){url="jdbc:sqlite:"+p.toAbsolutePath();}
 private Connection open()throws SQLException{Connection c=DriverManager.getConnection(url);try(Statement s=c.createStatement()){s.execute("PRAGMA busy_timeout=5000");s.execute("PRAGMA foreign_keys=ON");}return c;}
 void migrate(){try(Connection c=open();Statement s=c.createStatement()){s.execute("CREATE TABLE IF NOT EXISTS hardcraft_world_schema_version(version INTEGER PRIMARY KEY,applied_at TEXT NOT NULL)");s.execute("CREATE TABLE IF NOT EXISTS hardcraft_world_claims(id INTEGER PRIMARY KEY AUTOINCREMENT,owner_uuid TEXT NOT NULL,world TEXT NOT NULL,min_x INTEGER NOT NULL,max_x INTEGER NOT NULL,min_z INTEGER NOT NULL,max_z INTEGER NOT NULL,created_at INTEGER NOT NULL,UNIQUE(world,min_x,max_x,min_z,max_z))");s.execute("CREATE TABLE IF NOT EXISTS hardcraft_world_trust(claim_id INTEGER NOT NULL,player_uuid TEXT NOT NULL,PRIMARY KEY(claim_id,player_uuid),FOREIGN KEY(claim_id) REFERENCES hardcraft_world_claims(id) ON DELETE CASCADE)");s.execute("CREATE TABLE IF NOT EXISTS hardcraft_world_audit(id INTEGER PRIMARY KEY AUTOINCREMENT,claim_id INTEGER,actor_uuid TEXT NOT NULL,action TEXT NOT NULL,at INTEGER NOT NULL)");s.execute("INSERT OR IGNORE INTO hardcraft_world_schema_version VALUES(1,CURRENT_TIMESTAMP)");}catch(SQLException e){throw fail(e);}}
 List<Claim> all(){try(Connection c=open();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT id,owner_uuid,world,min_x,max_x,min_z,max_z FROM hardcraft_world_claims")){List<Claim> out=new ArrayList<>();while(r.next())out.add(new Claim(r.getLong(1),UUID.fromString(r.getString(2)),r.getString(3),r.getInt(4),r.getInt(5),r.getInt(6),r.getInt(7),trust(c,r.getLong(1))));return out;}catch(SQLException e){throw fail(e);}}
 Claim create(UUID o,String w,int a,int b,int c,int d){try(Connection x=open()){try(Statement begin=x.createStatement()){begin.execute("BEGIN IMMEDIATE");}try{for(Claim q:all(x))if(q.overlaps(new Claim(0,o,w,a,b,c,d,Set.of())))throw new IllegalArgumentException("claim overlaps #"+q.id());try(PreparedStatement s=x.prepareStatement("INSERT INTO hardcraft_world_claims(owner_uuid,world,min_x,max_x,min_z,max_z,created_at) VALUES(?,?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){s.setString(1,o.toString());s.setString(2,w);s.setInt(3,a);s.setInt(4,b);s.setInt(5,c);s.setInt(6,d);s.setLong(7,System.currentTimeMillis());s.executeUpdate();try(ResultSet k=s.getGeneratedKeys()){k.next();long id=k.getLong(1);audit(x,id,o,"CREATE");try(Statement end=x.createStatement()){end.execute("COMMIT");}return new Claim(id,o,w,a,b,c,d,Set.of());}}}catch(Exception e){try(Statement end=x.createStatement()){end.execute("ROLLBACK");}throw e;}}catch(Exception e){if(e instanceof RuntimeException r)throw r;throw fail(e);}}
 void delete(long id,UUID actor){change("DELETE FROM hardcraft_world_claims WHERE id=?",id,null,actor,"DELETE");}
 void trust(long id,UUID player,UUID actor,boolean add){change(add?"INSERT OR IGNORE INTO hardcraft_world_trust VALUES(?,?)":"DELETE FROM hardcraft_world_trust WHERE claim_id=? AND player_uuid=?",id,player,actor,add?"TRUST":"UNTRUST");}
 private void change(String sql,long id,UUID player,UUID actor,String action){try(Connection c=open()){c.setAutoCommit(false);try(PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,id);if(player!=null)s.setString(2,player.toString());s.executeUpdate();audit(c,id,actor,action);c.commit();}catch(Exception e){c.rollback();throw e;}}catch(Exception e){throw fail(e);}}
 private List<Claim> all(Connection c)throws SQLException{List<Claim> out=new ArrayList<>();try(Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT id,owner_uuid,world,min_x,max_x,min_z,max_z FROM hardcraft_world_claims")){while(r.next())out.add(new Claim(r.getLong(1),UUID.fromString(r.getString(2)),r.getString(3),r.getInt(4),r.getInt(5),r.getInt(6),r.getInt(7),trust(c,r.getLong(1))));}return out;}
 private Set<UUID> trust(Connection c,long id)throws SQLException{Set<UUID> x=new HashSet<>();try(PreparedStatement s=c.prepareStatement("SELECT player_uuid FROM hardcraft_world_trust WHERE claim_id=?")){s.setLong(1,id);try(ResultSet r=s.executeQuery()){while(r.next())x.add(UUID.fromString(r.getString(1)));}}return x;}
 private void audit(Connection c,long id,UUID actor,String action)throws SQLException{try(PreparedStatement s=c.prepareStatement("INSERT INTO hardcraft_world_audit(claim_id,actor_uuid,action,at) VALUES(?,?,?,?)")){s.setLong(1,id);s.setString(2,actor.toString());s.setString(3,action);s.setLong(4,System.currentTimeMillis());s.executeUpdate();}}
 private IllegalStateException fail(Exception e){return new IllegalStateException("World persistence failed: "+e.getMessage(),e);}
}