package com.hardcraft.skills;
import java.nio.file.Path;import java.util.*;import java.util.concurrent.*;import net.kyori.adventure.text.Component;import org.bukkit.*;import org.bukkit.block.Block;import org.bukkit.command.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.block.BlockBreakEvent;import org.bukkit.event.entity.EntityDeathEvent;import org.bukkit.plugin.java.JavaPlugin;
public final class HardCraftSkills extends JavaPlugin implements Listener,CommandExecutor{
 private SkillRepository repo;private ExecutorService db;private long[] levels;private int formula;private long cooldown;private final Map<String,Long> recent=new ConcurrentHashMap<>();
 public void onEnable(){saveDefaultConfig();formula=getConfig().getInt("formula-version");levels=getConfig().getLongList("levels").stream().mapToLong(Long::longValue).toArray();cooldown=getConfig().getLong("cooldown-millis");if(formula<1||levels.length<2||levels[0]!=0)throw new IllegalArgumentException("invalid skill formula");Path database=Objects.requireNonNull(getServer().getPluginManager().getPlugin("HardCraftCore")).getDataFolder().toPath().resolve("hardcraft.db");repo=new SkillRepository(database);repo.migrate();db=Executors.newSingleThreadExecutor(Thread.ofPlatform().name("HardCraftSkills-DB").factory());getServer().getPluginManager().registerEvents(this,this);Objects.requireNonNull(getCommand("skills")).setExecutor(this);}
 @EventHandler(ignoreCancelled=true) public void block(BlockBreakEvent e){Skill s=switch(e.getBlock().getType()){case WHEAT,CARROTS,POTATOES,BEETROOTS->Skill.FARMING;default->Skill.MINING;};String source=e.getPlayer().getUniqueId()+":"+location(e.getBlock());long now=System.currentTimeMillis(),previous=recent.getOrDefault(source,0L);if(now-previous<cooldown)return;recent.put(source,now);grant(e.getPlayer(),s,getConfig().getLong("xp."+s.name().toLowerCase()),"block:"+source+":"+(now/cooldown));}
 @EventHandler(ignoreCancelled=true) public void death(EntityDeathEvent e){Player p=e.getEntity().getKiller();if(p!=null)grant(p,Skill.COMBAT,getConfig().getLong("xp.combat"),"kill:"+e.getEntity().getUniqueId());}
 private void grant(Player p,Skill s,long xp,String key){CompletableFuture<SkillProgress> future=CompletableFuture.supplyAsync(()->repo.grant(p.getUniqueId(),s,xp,key,formula,levels),db);future.thenAccept(v->{if(v.xp()==levels[v.level()])Bukkit.getScheduler().runTask(this,()->p.sendMessage(Component.text("[Skills] "+s+" level "+v.level()+" unlocked")));});}
 public boolean onCommand(CommandSender sender,Command c,String l,String[] a){if(!(sender instanceof Player p)){sender.sendMessage(Component.text("Players only"));return true;}Skill s;try{s=a.length==0?Skill.MINING:Skill.valueOf(a[0].toUpperCase());}catch(Exception e){return false;}CompletableFuture<SkillProgress> future=CompletableFuture.supplyAsync(()->repo.find(p.getUniqueId(),s,levels,formula),db);future.thenAccept(v->Bukkit.getScheduler().runTask(this,()->{long next=v.level()+1<levels.length?levels[v.level()+1]:v.xp();p.sendMessage(Component.text("[Skills] "+s+" level "+v.level()+" XP "+v.xp()+"; next "+Math.max(0,next-v.xp())+"; unlock level "+Math.min(v.level()+1,levels.length-1)));}));return true;}
 private String location(Block b){return b.getWorld().getUID()+":"+b.getX()+":"+b.getY()+":"+b.getZ();}public void onDisable(){if(db!=null)db.shutdown();}
}