package com.hardcraft.skills;
import java.nio.file.*;import java.sql.*;import java.util.*;
final class SkillRepository{
 private final String url;SkillRepository(Path p){url="jdbc:sqlite:"+p.toAbsolutePath();}
 void migrate(){try{Path p=Path.of(url.substring(12));if(p.getParent()!=null)Files.createDirectories(p.getParent());try(Connection c=open();Statement s=c.createStatement()){s.execute("CREATE TABLE IF NOT EXISTS hardcraft_skills_progress(owner_uuid TEXT NOT NULL,skill TEXT NOT NULL,xp INTEGER NOT NULL CHECK(xp>=0),level INTEGER NOT NULL CHECK(level>=0),formula_version INTEGER NOT NULL,PRIMARY KEY(owner_uuid,skill))");s.execute("CREATE TABLE IF NOT EXISTS hardcraft_skills_grants(event_key TEXT PRIMARY KEY,owner_uuid TEXT NOT NULL,skill TEXT NOT NULL,xp INTEGER NOT NULL,created_at INTEGER NOT NULL)");s.execute("CREATE TABLE IF NOT EXISTS hardcraft_skills_unlocks(owner_uuid TEXT NOT NULL,skill TEXT NOT NULL,level INTEGER NOT NULL,unlocked_at INTEGER NOT NULL,PRIMARY KEY(owner_uuid,skill,level))");}}catch(Exception e){throw new IllegalStateException("Skills migration failed",e);}}
 synchronized SkillProgress grant(UUID owner,Skill skill,long amount,String key,int version,long[] levels){if(amount<=0||key==null||key.isBlank())throw new IllegalArgumentException("invalid XP grant");try(Connection c=open()){c.setAutoCommit(false);try{try(PreparedStatement s=c.prepareStatement("INSERT OR IGNORE INTO hardcraft_skills_grants VALUES(?,?,?,?,?)")){s.setString(1,key);s.setString(2,owner.toString());s.setString(3,skill.name());s.setLong(4,amount);s.setLong(5,System.currentTimeMillis());if(s.executeUpdate()==0){c.rollback();return find(owner,skill,levels,version);}}SkillProgress old=find(c,owner,skill,levels,version);long xp=Math.addExact(old.xp(),amount);int level=level(xp,levels);try(PreparedStatement s=c.prepareStatement("INSERT INTO hardcraft_skills_progress VALUES(?,?,?,?,?) ON CONFLICT(owner_uuid,skill) DO UPDATE SET xp=excluded.xp,level=excluded.level,formula_version=excluded.formula_version")){s.setString(1,owner.toString());s.setString(2,skill.name());s.setLong(3,xp);s.setInt(4,level);s.setInt(5,version);s.executeUpdate();}for(int i=old.level()+1;i<=level;i++)try(PreparedStatement s=c.prepareStatement("INSERT OR IGNORE INTO hardcraft_skills_unlocks VALUES(?,?,?,?)")){s.setString(1,owner.toString());s.setString(2,skill.name());s.setInt(3,i);s.setLong(4,System.currentTimeMillis());s.executeUpdate();}c.commit();return new SkillProgress(skill,xp,level,version);}catch(Exception e){c.rollback();throw e;}}catch(Exception e){throw new IllegalStateException("XP grant failed",e);}}
 SkillProgress find(UUID owner,Skill skill,long[] levels,int version){try(Connection c=open()){return find(c,owner,skill,levels,version);}catch(SQLException e){throw new IllegalStateException("skill lookup failed",e);}}
 private SkillProgress find(Connection c,UUID owner,Skill skill,long[] levels,int version)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT xp FROM hardcraft_skills_progress WHERE owner_uuid=? AND skill=?")){s.setString(1,owner.toString());s.setString(2,skill.name());try(ResultSet r=s.executeQuery()){long xp=r.next()?r.getLong(1):0;return new SkillProgress(skill,xp,level(xp,levels),version);}}}
 static int level(long xp,long[] levels){int level=0;while(level+1<levels.length&&xp>=levels[level+1])level++;return level;}
 private Connection open()throws SQLException{Connection c=DriverManager.getConnection(url);try(Statement s=c.createStatement()){s.execute("PRAGMA busy_timeout=5000");}return c;}
}