package com.hardcraft.mobs;
import java.nio.file.*;import java.util.*;import java.util.concurrent.*;import org.bukkit.*;import org.bukkit.attribute.Attribute;import org.bukkit.command.*;import org.bukkit.configuration.ConfigurationSection;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.entity.*;import org.bukkit.event.player.*;import org.bukkit.inventory.ItemStack;import org.bukkit.persistence.PersistentDataType;import org.bukkit.plugin.java.JavaPlugin;
public final class HardCraftMobs extends JavaPlugin implements Listener,CommandExecutor{
 private record Encounter(BossDefinition definition,Map<UUID,Double> damage,double maximum){}
 private final Map<UUID,Encounter> active=new HashMap<>();private final Map<String,BossDefinition> definitions=new HashMap<>();private ExecutorService db;private LootRepository loot;private NamespacedKey bossKey;private Material lootMaterial;private int lootAmount;
 @Override public void onEnable(){saveDefaultConfig();loadDefinitions();Path path=Objects.requireNonNull(getServer().getPluginManager().getPlugin("HardCraftCore")).getDataFolder().toPath().resolve("hardcraft.db");loot=new LootRepository(path);loot.migrate();int uncertain=loot.recoverUncertain();if(uncertain>0)getLogger().severe(uncertain+" loot deliveries UNCERTAIN; inspect hardcraft_mob_loot_audit before reconciliation");db=Executors.newSingleThreadExecutor(Thread.ofPlatform().name("HardCraftMobs-DB").factory());bossKey=new NamespacedKey(this,"boss_id");getServer().getPluginManager().registerEvents(this,this);Objects.requireNonNull(getCommand("hcmob")).setExecutor(this);for(World w:Bukkit.getWorlds())for(Entity e:w.getEntities())if(e.getPersistentDataContainer().has(bossKey)){e.remove();getLogger().warning("Removed unfinished boss "+e.getUniqueId()+" after restart; no loot awarded");}new StagingProbe(this,loot,db,bossKey).run();}
 private void loadDefinitions(){ConfigurationSection bosses=Objects.requireNonNull(getConfig().getConfigurationSection("bosses"));for(String id:bosses.getKeys(false)){ConfigurationSection c=Objects.requireNonNull(bosses.getConfigurationSection(id));definitions.put(id,new BossDefinition(id,c.getDouble("base-health"),c.getDouble("health-per-player"),c.getDoubleList("phases"),c.getDouble("participation-min-damage")));EntityType.valueOf(c.getString("entity","IRON_GOLEM"));lootMaterial=Material.valueOf(c.getString("loot.material","DIAMOND"));lootAmount=c.getInt("loot.amount",1);}}
 @Override public boolean onCommand(CommandSender sender,Command command,String label,String[] args){if(!(sender instanceof Player p)||args.length!=2||!args[0].equalsIgnoreCase("spawn"))return false;BossDefinition d=definitions.get(args[1]);if(d==null){sender.sendMessage("Unknown boss ID");return true;}LivingEntity e=(LivingEntity)p.getWorld().spawnEntity(p.getLocation(),EntityType.valueOf(getConfig().getString("bosses."+d.id()+".entity","IRON_GOLEM")));int players=Math.max(1,e.getWorld().getNearbyPlayers(e.getLocation(),32).size());double maximum=d.maximumHealth(players);e.getAttribute(Attribute.MAX_HEALTH).setBaseValue(maximum);e.setHealth(maximum);e.customName(net.kyori.adventure.text.Component.text(getConfig().getString("bosses."+d.id()+".name",d.id())));e.getPersistentDataContainer().set(bossKey,PersistentDataType.STRING,d.id());active.put(e.getUniqueId(),new Encounter(d,new HashMap<>(),maximum));return true;}
 @EventHandler(ignoreCancelled=true) public void damage(EntityDamageByEntityEvent event){Encounter encounter=active.get(event.getEntity().getUniqueId());if(encounter==null||!(event.getDamager() instanceof Player player))return;encounter.damage().merge(player.getUniqueId(),event.getFinalDamage(),Double::sum);LivingEntity boss=(LivingEntity)event.getEntity();int phase=encounter.definition().phase(Math.max(1,boss.getHealth()-event.getFinalDamage()),encounter.maximum());boss.getPersistentDataContainer().set(new NamespacedKey(this,"phase"),PersistentDataType.INTEGER,phase);}
 @EventHandler public void quit(PlayerQuitEvent event){for(var entry:new ArrayList<>(active.entrySet())){Entity entity=Bukkit.getEntity(entry.getKey());if(!(entity instanceof LivingEntity boss))continue;Encounter old=entry.getValue();int players=Math.max(1,boss.getWorld().getNearbyPlayers(boss.getLocation(),32).size()-1);double maximum=old.definition().maximumHealth(players),health=old.definition().rescale(boss.getHealth(),old.maximum(),players);boss.getAttribute(Attribute.MAX_HEALTH).setBaseValue(maximum);boss.setHealth(health);active.put(entry.getKey(),new Encounter(old.definition(),old.damage(),maximum));}}
 @EventHandler public void death(EntityDeathEvent event){Encounter encounter=active.remove(event.getEntity().getUniqueId());if(encounter==null)return;event.getDrops().clear();UUID entity=event.getEntity().getUniqueId();for(UUID player:BossRules.eligible(encounter.damage(),encounter.definition().minimumDamage()))CompletableFuture.runAsync(()->loot.create(entity,player,encounter.definition().id()),db).thenRun(()->Bukkit.getScheduler().runTask(this,()->deliver(Bukkit.getPlayer(player),entity)));}
 @EventHandler public void join(PlayerJoinEvent event){CompletableFuture.supplyAsync(()->loot.pending(event.getPlayer().getUniqueId()),db).thenAccept(all->Bukkit.getScheduler().runTask(this,()->all.forEach(c->deliver(event.getPlayer(),c.entity()))));}
 private void deliver(Player player,UUID entity){if(player==null||!player.isOnline()||player.getInventory().firstEmpty()<0)return;UUID owner=player.getUniqueId();CompletableFuture.supplyAsync(()->loot.begin(entity,owner),db).thenAccept(started->Bukkit.getScheduler().runTask(this,()->{if(!started||!player.isOnline())return;var leftover=player.getInventory().addItem(new ItemStack(lootMaterial,lootAmount));if(!leftover.isEmpty()){getLogger().severe("Loot delivery UNCERTAIN for "+owner+" entity "+entity+"; audit required");return;}CompletableFuture.runAsync(()->loot.delivered(entity,owner),db);}));}
 @Override public void onDisable(){if(db!=null){db.shutdown();try{if(!db.awaitTermination(10,TimeUnit.SECONDS))getLogger().severe("Timed out waiting for loot claims");}catch(InterruptedException e){Thread.currentThread().interrupt();}}}
}