package com.hardcraft.mobs;
import java.nio.file.*;import java.sql.*;import java.util.*;
final class LootRepository{
 enum State{PENDING,DELIVERING,DELIVERED,UNCERTAIN} record Claim(UUID entity,UUID player,String boss,State state){}
 private final String url;LootRepository(Path p){url="jdbc:sqlite:"+p.toAbsolutePath();}
 void migrate(){try{Path p=Path.of(url.substring(12));Files.createDirectories(p.getParent());try(Connection c=open();Statement s=c.createStatement()){s.execute("CREATE TABLE IF NOT EXISTS hardcraft_mob_loot(entity_uuid TEXT NOT NULL,player_uuid TEXT NOT NULL,boss_id TEXT NOT NULL,created_at INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'PENDING',updated_at INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(entity_uuid,player_uuid))");try{s.execute("ALTER TABLE hardcraft_mob_loot ADD COLUMN status TEXT NOT NULL DEFAULT 'DELIVERED'");}catch(SQLException ignored){}try{s.execute("ALTER TABLE hardcraft_mob_loot ADD COLUMN updated_at INTEGER NOT NULL DEFAULT 0");}catch(SQLException ignored){}s.execute("CREATE TABLE IF NOT EXISTS hardcraft_mob_loot_audit(id INTEGER PRIMARY KEY AUTOINCREMENT,entity_uuid TEXT NOT NULL,player_uuid TEXT NOT NULL,from_status TEXT,to_status TEXT NOT NULL,reason TEXT NOT NULL,created_at INTEGER NOT NULL)");}}catch(Exception e){throw new IllegalStateException("Mobs migration failed",e);}}
 synchronized boolean create(UUID e,UUID p,String boss){try(Connection c=open()){c.setAutoCommit(false);try(PreparedStatement s=c.prepareStatement("INSERT OR IGNORE INTO hardcraft_mob_loot(entity_uuid,player_uuid,boss_id,created_at,status,updated_at) VALUES(?,?,?,?,'PENDING',?)")){long now=System.currentTimeMillis();s.setString(1,e.toString());s.setString(2,p.toString());s.setString(3,boss);s.setLong(4,now);s.setLong(5,now);boolean made=s.executeUpdate()==1;if(made)audit(c,e,p,null,State.PENDING,"boss-death");c.commit();return made;}}catch(Exception x){throw fail(x);}}
 synchronized boolean begin(UUID e,UUID p){return move(e,p,State.PENDING,State.DELIVERING,"inventory-delivery-started");} synchronized void delivered(UUID e,UUID p){if(!move(e,p,State.DELIVERING,State.DELIVERED,"inventory-delivery-confirmed"))throw new IllegalStateException("loot not delivering");}
 synchronized int recoverUncertain(){try(Connection c=open()){c.setAutoCommit(false);var xs=list(c,State.DELIVERING,null);for(Claim x:xs)update(c,x,State.UNCERTAIN,"startup-crash-window");c.commit();return xs.size();}catch(Exception e){throw fail(e);}}
 synchronized List<Claim> pending(UUID p){try(Connection c=open()){return list(c,State.PENDING,p);}catch(Exception e){throw fail(e);}} synchronized State state(UUID e,UUID p){try(Connection c=open();PreparedStatement s=c.prepareStatement("SELECT status FROM hardcraft_mob_loot WHERE entity_uuid=? AND player_uuid=?")){s.setString(1,e.toString());s.setString(2,p.toString());try(ResultSet r=s.executeQuery()){return r.next()?State.valueOf(r.getString(1)):null;}}catch(Exception x){throw fail(x);}}
 private boolean move(UUID e,UUID p,State from,State to,String reason){try(Connection c=open()){c.setAutoCommit(false);try(PreparedStatement s=c.prepareStatement("UPDATE hardcraft_mob_loot SET status=?,updated_at=? WHERE entity_uuid=? AND player_uuid=? AND status=?")){s.setString(1,to.name());s.setLong(2,System.currentTimeMillis());s.setString(3,e.toString());s.setString(4,p.toString());s.setString(5,from.name());if(s.executeUpdate()!=1){c.rollback();return false;}audit(c,e,p,from,to,reason);c.commit();return true;}}catch(Exception x){throw fail(x);}}
 private void update(Connection c,Claim x,State to,String reason)throws SQLException{try(PreparedStatement s=c.prepareStatement("UPDATE hardcraft_mob_loot SET status=?,updated_at=? WHERE entity_uuid=? AND player_uuid=?")){s.setString(1,to.name());s.setLong(2,System.currentTimeMillis());s.setString(3,x.entity().toString());s.setString(4,x.player().toString());s.executeUpdate();}audit(c,x.entity(),x.player(),x.state(),to,reason);}
 private List<Claim> list(Connection c,State state,UUID player)throws SQLException{String q="SELECT entity_uuid,player_uuid,boss_id,status FROM hardcraft_mob_loot WHERE status=?"+(player==null?"":" AND player_uuid=?");try(PreparedStatement s=c.prepareStatement(q)){s.setString(1,state.name());if(player!=null)s.setString(2,player.toString());try(ResultSet r=s.executeQuery()){var out=new ArrayList<Claim>();while(r.next())out.add(new Claim(UUID.fromString(r.getString(1)),UUID.fromString(r.getString(2)),r.getString(3),State.valueOf(r.getString(4))));return out;}}}
 private void audit(Connection c,UUID e,UUID p,State from,State to,String reason)throws SQLException{try(PreparedStatement s=c.prepareStatement("INSERT INTO hardcraft_mob_loot_audit(entity_uuid,player_uuid,from_status,to_status,reason,created_at) VALUES(?,?,?,?,?,?)")){s.setString(1,e.toString());s.setString(2,p.toString());s.setString(3,from==null?null:from.name());s.setString(4,to.name());s.setString(5,reason);s.setLong(6,System.currentTimeMillis());s.executeUpdate();}}
 private Connection open()throws SQLException{Connection c=DriverManager.getConnection(url);try(Statement s=c.createStatement()){s.execute("PRAGMA busy_timeout=5000");}return c;}private IllegalStateException fail(Exception e){return new IllegalStateException("Loot persistence failed",e);}
}