package com.hardcraft.mobs;
import java.nio.file.*;import java.util.*;import java.util.concurrent.*;import org.bukkit.*;import org.bukkit.entity.*;import org.bukkit.persistence.PersistentDataType;
final class StagingProbe{
 private static final UUID PLAYER=UUID.fromString("00000000-0000-0000-0000-000000000801");private final HardCraftMobs plugin;private final LootRepository loot;private final Executor executor;private final NamespacedKey key;private final Path marker;
 StagingProbe(HardCraftMobs p,LootRepository r,Executor e,NamespacedKey k){plugin=p;loot=r;executor=e;key=k;marker=p.getDataFolder().toPath().resolve("staging-probe-entity");}
 void run(){if(!Boolean.getBoolean("hardcraft.mobs.stagingProbe"))return;Bukkit.getScheduler().runTask(plugin,()->{try{if(Files.exists(marker))verify();else prepare();}catch(Throwable e){fail(e);}});}
 private void prepare()throws Exception{World world=Bukkit.getWorlds().getFirst();LivingEntity boss=(LivingEntity)world.spawnEntity(world.getSpawnLocation(),EntityType.IRON_GOLEM);boss.getPersistentDataContainer().set(key,PersistentDataType.STRING,"stone_titan");UUID entity=boss.getUniqueId();CompletableFuture.supplyAsync(()->loot.create(entity,PLAYER,"stone_titan"),executor).whenComplete((first,error)->Bukkit.getScheduler().runTask(plugin,()->{try{if(error!=null)throw new CompletionException(error);if(!first)throw new IllegalStateException("initial loot claim duplicated");Files.createDirectories(marker.getParent());Files.writeString(marker,entity.toString());plugin.getLogger().info("STAGING_PROBE PREPARED: tagged entity and pending loot persisted; restart required");Bukkit.shutdown();}catch(Throwable e){fail(e);}}));}
 private void verify()throws Exception{UUID entity=UUID.fromString(Files.readString(marker).trim());if(Bukkit.getEntity(entity)!=null)throw new IllegalStateException("unfinished boss survived restart");CompletableFuture.supplyAsync(()->loot.pending(PLAYER),executor).whenComplete((pending,error)->Bukkit.getScheduler().runTask(plugin,()->{try{if(error!=null)throw new CompletionException(error);if(pending.size()!=1||!pending.getFirst().entity().equals(entity)||loot.create(entity,PLAYER,"stone_titan"))throw new IllegalStateException("pending loot recovery failed");Files.delete(marker);plugin.getLogger().info("STAGING_PROBE PASS: unfinished entity removed; pending loot survived exactly once");Bukkit.shutdown();}catch(Throwable e){fail(e);}}));}
 private void fail(Throwable e){plugin.getLogger().log(java.util.logging.Level.SEVERE,"STAGING_PROBE FAIL",e);Bukkit.shutdown();}
}