package com.hardcraft.events;
import java.nio.file.*;import java.sql.*;import java.util.*;
final class EventRepository{
 private final String url;EventRepository(Path path){url="jdbc:sqlite:"+path.toAbsolutePath();}
 void migrate(){try{Path p=Path.of(url.substring(12));if(p.getParent()!=null)Files.createDirectories(p.getParent());try(Connection c=open();Statement s=c.createStatement()){s.execute("CREATE TABLE IF NOT EXISTS hardcraft_events(id TEXT PRIMARY KEY,state TEXT NOT NULL,material TEXT NOT NULL,target INTEGER NOT NULL CHECK(target>0),progress INTEGER NOT NULL DEFAULT 0 CHECK(progress>=0),reward INTEGER NOT NULL CHECK(reward>=0),starts_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)");s.execute("CREATE TABLE IF NOT EXISTS hardcraft_event_transitions(seq INTEGER PRIMARY KEY AUTOINCREMENT,event_id TEXT NOT NULL,from_state TEXT,to_state TEXT NOT NULL,actor TEXT NOT NULL,at INTEGER NOT NULL)");s.execute("CREATE TABLE IF NOT EXISTS hardcraft_event_contributions(id TEXT PRIMARY KEY,event_id TEXT NOT NULL,owner_uuid TEXT NOT NULL,material TEXT NOT NULL,amount INTEGER NOT NULL CHECK(amount>0),status TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)");s.execute("CREATE TABLE IF NOT EXISTS hardcraft_event_rewards(event_id TEXT NOT NULL,owner_uuid TEXT NOT NULL,status TEXT NOT NULL,updated_at INTEGER NOT NULL,PRIMARY KEY(event_id,owner_uuid))");}}catch(Exception e){throw new IllegalStateException("Events migration failed",e);}}
 synchronized EventSnapshot schedule(String id,String material,long target,long reward,long startsAt,String actor){if(id==null||!id.matches("[a-z0-9_-]+")||material==null||target<1||reward<0)throw new IllegalArgumentException("invalid event");try(Connection c=open()){c.setAutoCommit(false);try(PreparedStatement s=c.prepareStatement("INSERT OR IGNORE INTO hardcraft_events VALUES(?,?,?,?,0,?,?,?)")){long now=System.currentTimeMillis();s.setString(1,id);s.setString(2,EventState.SCHEDULED.name());s.setString(3,material);s.setLong(4,target);s.setLong(5,reward);s.setLong(6,startsAt);s.setLong(7,now);if(s.executeUpdate()==1)audit(c,id,null,EventState.SCHEDULED,actor,now);}EventSnapshot e=find(c,id);c.commit();return e;}catch(Exception e){throw fail("schedule",e);}}
 synchronized EventSnapshot transition(String id,EventState to,String actor){try(Connection c=open()){c.setAutoCommit(false);EventSnapshot e=find(c,id);if(!allowed(e.state(),to)||to==EventState.REWARDING&&e.progress()<e.target())throw new IllegalStateException("invalid transition "+e.state()+" to "+to);long now=System.currentTimeMillis();try(PreparedStatement s=c.prepareStatement("UPDATE hardcraft_events SET state=?,updated_at=? WHERE id=? AND state=?")){s.setString(1,to.name());s.setLong(2,now);s.setString(3,id);s.setString(4,e.state().name());if(s.executeUpdate()!=1)throw new IllegalStateException("concurrent transition");}audit(c,id,e.state(),to,actor,now);if(to==EventState.CANCELLED)try(PreparedStatement s=c.prepareStatement("UPDATE hardcraft_event_contributions SET status='REFUND_PENDING',updated_at=? WHERE event_id=? AND status='ACCEPTED'")){s.setLong(1,now);s.setString(2,id);s.executeUpdate();}c.commit();return find(id);}catch(Exception e){throw fail("transition",e);}}
 synchronized String reserve(String eventId,UUID owner,String material,int amount){if(amount<1)throw new IllegalArgumentException("invalid amount");try(Connection c=open()){EventSnapshot e=find(c,eventId);if(e.state()!=EventState.ACTIVE||!e.material().equals(material))throw new IllegalStateException("event not accepting material");long pending;try(PreparedStatement q=c.prepareStatement("SELECT COALESCE(SUM(amount),0) FROM hardcraft_event_contributions WHERE event_id=? AND status='PENDING'")){q.setString(1,eventId);try(ResultSet r=q.executeQuery()){pending=r.next()?r.getLong(1):0;}}if(amount>e.target()-e.progress()-pending)throw new IllegalStateException("target capacity changed; retry");String id=UUID.randomUUID().toString();try(PreparedStatement s=c.prepareStatement("INSERT INTO hardcraft_event_contributions VALUES(?,?,?,?,?,'PENDING',?,?)")){long now=System.currentTimeMillis();s.setString(1,id);s.setString(2,eventId);s.setString(3,owner.toString());s.setString(4,material);s.setInt(5,amount);s.setLong(6,now);s.setLong(7,now);s.executeUpdate();}return id;}catch(Exception e){throw fail("reserve contribution",e);}}
 synchronized EventSnapshot accept(String contributionId){try(Connection c=open()){c.setAutoCommit(false);String event;int amount;try(PreparedStatement s=c.prepareStatement("SELECT event_id,amount,status FROM hardcraft_event_contributions WHERE id=?")){s.setString(1,contributionId);try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalArgumentException("unknown contribution");event=r.getString(1);amount=r.getInt(2);if(r.getString(3).equals("ACCEPTED")){c.rollback();return find(event);}if(!r.getString(3).equals("PENDING"))throw new IllegalStateException("contribution requires review");}}try(PreparedStatement s=c.prepareStatement("UPDATE hardcraft_event_contributions SET status='ACCEPTED',updated_at=? WHERE id=? AND status='PENDING'")){s.setLong(1,System.currentTimeMillis());s.setString(2,contributionId);s.executeUpdate();}try(PreparedStatement s=c.prepareStatement("UPDATE hardcraft_events SET progress=MIN(target,progress+?),updated_at=? WHERE id=? AND state='ACTIVE'")){s.setInt(1,amount);s.setLong(2,System.currentTimeMillis());s.setString(3,event);if(s.executeUpdate()!=1)throw new IllegalStateException("event no longer active");}c.commit();return find(event);}catch(Exception e){throw fail("accept contribution",e);}}
 synchronized void review(String contributionId){setContribution(contributionId,"PENDING","REVIEW_REQUIRED");}
 synchronized boolean reserveRefund(String contributionId,UUID owner){try(Connection c=open();PreparedStatement s=c.prepareStatement("UPDATE hardcraft_event_contributions SET status='REFUNDING',updated_at=? WHERE id=? AND owner_uuid=? AND status='REFUND_PENDING'")){s.setLong(1,System.currentTimeMillis());s.setString(2,contributionId);s.setString(3,owner.toString());return s.executeUpdate()==1;}catch(Exception e){throw fail("refund reservation",e);}}
 synchronized void finishRefund(String contributionId,UUID owner){try(Connection c=open();PreparedStatement s=c.prepareStatement("UPDATE hardcraft_event_contributions SET status='REFUNDED',updated_at=? WHERE id=? AND owner_uuid=? AND status='REFUNDING'")){s.setLong(1,System.currentTimeMillis());s.setString(2,contributionId);s.setString(3,owner.toString());if(s.executeUpdate()!=1)throw new IllegalStateException("refund not reserved");}catch(Exception e){throw fail("refund",e);}}
 synchronized boolean reserveReward(String event,UUID owner){try(Connection c=open()){EventState state=find(c,event).state();if(state!=EventState.REWARDING&&state!=EventState.FINISHED)throw new IllegalStateException("rewards unavailable");try(PreparedStatement eligible=c.prepareStatement("SELECT 1 FROM hardcraft_event_contributions WHERE event_id=? AND owner_uuid=? AND status='ACCEPTED' LIMIT 1")){eligible.setString(1,event);eligible.setString(2,owner.toString());try(ResultSet r=eligible.executeQuery()){if(!r.next())throw new IllegalStateException("not a participant");}}try(PreparedStatement s=c.prepareStatement("INSERT OR IGNORE INTO hardcraft_event_rewards VALUES(?,?,'PENDING',?)")){s.setString(1,event);s.setString(2,owner.toString());s.setLong(3,System.currentTimeMillis());s.executeUpdate();}try(PreparedStatement s=c.prepareStatement("SELECT status FROM hardcraft_event_rewards WHERE event_id=? AND owner_uuid=?")){s.setString(1,event);s.setString(2,owner.toString());try(ResultSet r=s.executeQuery()){return r.next()&&r.getString(1).equals("PENDING");}}}catch(Exception e){throw fail("reward",e);}}
 synchronized void markRewardPaid(String event,UUID owner){try(Connection c=open();PreparedStatement s=c.prepareStatement("UPDATE hardcraft_event_rewards SET status='PAID',updated_at=? WHERE event_id=? AND owner_uuid=? AND status='PENDING'")){s.setLong(1,System.currentTimeMillis());s.setString(2,event);s.setString(3,owner.toString());if(s.executeUpdate()!=1)throw new IllegalStateException("reward not pending");}catch(Exception e){throw fail("reward completion",e);}}
 EventSnapshot find(String id){try(Connection c=open()){return find(c,id);}catch(Exception e){throw fail("lookup",e);}}
 List<RefundWork> pendingRefunds(UUID owner){try(Connection c=open();PreparedStatement s=c.prepareStatement("SELECT id,material,amount FROM hardcraft_event_contributions WHERE owner_uuid=? AND status='REFUND_PENDING' ORDER BY created_at")){s.setString(1,owner.toString());try(ResultSet r=s.executeQuery()){List<RefundWork>x=new ArrayList<>();while(r.next())x.add(new RefundWork(r.getString(1),r.getString(2),r.getInt(3)));return x;}}catch(Exception e){throw fail("refund lookup",e);}}
 int auditCount(String id){try(Connection c=open();PreparedStatement s=c.prepareStatement("SELECT COUNT(*) FROM hardcraft_event_transitions WHERE event_id=?")){s.setString(1,id);try(ResultSet r=s.executeQuery()){return r.next()?r.getInt(1):0;}}catch(Exception e){throw fail("audit lookup",e);}}
 private void setContribution(String id,String from,String to){try(Connection c=open();PreparedStatement s=c.prepareStatement("UPDATE hardcraft_event_contributions SET status=?,updated_at=? WHERE id=? AND status=?")){s.setString(1,to);s.setLong(2,System.currentTimeMillis());s.setString(3,id);s.setString(4,from);if(s.executeUpdate()!=1)throw new IllegalStateException("contribution state changed");}catch(Exception e){throw fail("contribution recovery",e);}}
 private EventSnapshot find(Connection c,String id)throws SQLException{try(PreparedStatement s=c.prepareStatement("SELECT state,material,target,progress,reward,starts_at FROM hardcraft_events WHERE id=?")){s.setString(1,id);try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalArgumentException("unknown event");return new EventSnapshot(id,EventState.valueOf(r.getString(1)),r.getString(2),r.getLong(3),r.getLong(4),r.getLong(5),r.getLong(6));}}}
 private void audit(Connection c,String id,EventState from,EventState to,String actor,long now)throws SQLException{try(PreparedStatement s=c.prepareStatement("INSERT INTO hardcraft_event_transitions(event_id,from_state,to_state,actor,at) VALUES(?,?,?,?,?)")){s.setString(1,id);s.setString(2,from==null?null:from.name());s.setString(3,to.name());s.setString(4,actor);s.setLong(5,now);s.executeUpdate();}}
 private static boolean allowed(EventState a,EventState b){return b==EventState.CANCELLED&&a!=EventState.FINISHED&&a!=EventState.CANCELLED||a==EventState.SCHEDULED&&b==EventState.ANNOUNCED||a==EventState.ANNOUNCED&&b==EventState.ACTIVE||a==EventState.ACTIVE&&b==EventState.REWARDING||a==EventState.REWARDING&&b==EventState.FINISHED;}
 private Connection open()throws SQLException{Connection c=DriverManager.getConnection(url);try(Statement s=c.createStatement()){s.execute("PRAGMA busy_timeout=5000");s.execute("PRAGMA foreign_keys=ON");}return c;}
 private IllegalStateException fail(String action,Exception e){return e instanceof IllegalStateException i?i:new IllegalStateException("Event "+action+" failed",e);}
}