package com.hardcraft.events;
import com.hardcraft.economy.api.EconomyApi;import java.nio.file.Path;import java.util.*;import java.util.concurrent.*;import java.util.logging.Level;import net.kyori.adventure.text.Component;import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import org.bukkit.inventory.ItemStack;import org.bukkit.plugin.java.JavaPlugin;
public final class HardCraftEvents extends JavaPlugin implements CommandExecutor{
 private EventRepository repo;private EconomyApi economy;private ExecutorService db;private String eventId="community_drive";private Material material;private long target,reward;
 public void onEnable(){try{saveDefaultConfig();material=Material.valueOf(getConfig().getString("event.material","COBBLESTONE"));target=getConfig().getLong("event.target");reward=getConfig().getLong("event.reward-money");economy=Objects.requireNonNull(getServer().getServicesManager().getRegistration(EconomyApi.class),"Economy API unavailable").getProvider();JavaPlugin core=(JavaPlugin)Objects.requireNonNull(getServer().getPluginManager().getPlugin("HardCraftCore"));Path path=core.getDataFolder().toPath().resolve("hardcraft.db");repo=new EventRepository(path);repo.migrate();db=Executors.newSingleThreadExecutor(Thread.ofPlatform().name("HardCraftEvents-DB").factory());Objects.requireNonNull(getCommand("event")).setExecutor(this);Objects.requireNonNull(getCommand("eventadmin")).setExecutor(this);resume();getLogger().info("HardCraftEvents v"+getPluginMeta().getVersion()+" enabled; schema=1");}catch(RuntimeException e){getLogger().log(Level.SEVERE,"HardCraftEvents failed to start",e);getServer().getPluginManager().disablePlugin(this);}}
 private void resume(){async(()->{try{EventSnapshot e=repo.find(eventId);if(e.state()==EventState.ACTIVE||e.state()==EventState.REWARDING)getLogger().info("Resumed "+e.id()+" in "+e.state()+" without replaying announcements or rewards");}catch(IllegalArgumentException ignored){}return null;});}
 public boolean onCommand(CommandSender sender,Command command,String label,String[] args){if(command.getName().equals("eventadmin"))return admin(sender,args);if(!(sender instanceof Player p)){sender.sendMessage("Players only");return true;}String action=args.length==0?"status":args[0].toLowerCase(Locale.ROOT);if(action.equals("status")){status(p);return true;}if(action.equals("contribute")&&args.length==2){int requested;try{requested=Integer.parseInt(args[1]);}catch(NumberFormatException e){p.sendMessage("Invalid amount");return true;}contribute(p,requested);return true;}if(action.equals("reward")){reward(p);return true;}if(action.equals("refund")){refund(p);return true;}return false;}
 private boolean admin(CommandSender sender,String[] args){if(!sender.hasPermission("hardcraft.events.admin")){sender.sendMessage("No permission");return true;}if(args.length<1)return false;String actor=sender.getName(),action=args[0].toLowerCase(Locale.ROOT),id=args.length>1?args[1]:eventId;async(()->switch(action){case "schedule"->repo.schedule(id,material.name(),target,reward,System.currentTimeMillis(),actor);case "announce"->repo.transition(id,EventState.ANNOUNCED,actor);case "start"->repo.transition(id,EventState.ACTIVE,actor);case "reward"->repo.transition(id,EventState.REWARDING,actor);case "finish"->repo.transition(id,EventState.FINISHED,actor);case "cancel"->repo.transition(id,EventState.CANCELLED,actor);case "inspect"->repo.find(id);default->throw new IllegalArgumentException("unknown action");}).thenAccept(e->main(()->sender.sendMessage("[Events] "+e))).exceptionally(this::failure);return true;}
 private void status(Player p){async(()->repo.find(eventId)).thenAccept(e->main(()->p.sendMessage(Component.text("[Events] "+e.state()+" "+e.progress()+"/"+e.target()+" "+e.material())))).exceptionally(this::failure);}
 private void contribute(Player p,int requested){if(requested<1){p.sendMessage("Invalid amount");return;}async(()->repo.find(eventId)).thenAccept(e->main(()->{if(e.state()!=EventState.ACTIVE){p.sendMessage("Event is not active");return;}int available=count(p,material),amount=(int)Math.min(Math.min(requested,available),e.target()-e.progress());if(amount<1){p.sendMessage("No required items or target already reached");return;}async(()->repo.reserve(eventId,p.getUniqueId(),material.name(),amount)).thenAccept(id->main(()->{int removed=remove(p,material,amount);if(removed!=amount){async(()->{repo.review(id);return null;});p.sendMessage("Contribution locked for admin review; inventory changed during submission");return;}async(()->repo.accept(id)).thenAccept(done->main(()->{p.sendMessage("[Events] Accepted "+amount+" "+material);if(done.progress()>=done.target())Bukkit.broadcast(Component.text("[Events] Community target reached"));})).exceptionally(ex->{async(()->{repo.review(id);return null;});return failure(ex);});})).exceptionally(this::failure);})).exceptionally(this::failure);}
 private void reward(Player p){async(()->repo.reserveReward(eventId,p.getUniqueId())).thenCompose(pending->{if(!pending)throw new IllegalStateException("reward already paid");return economy.earn(p.getUniqueId(),reward,"event:"+eventId+":"+p.getUniqueId()+":money:v1");}).thenCompose(x->async(()->{repo.markRewardPaid(eventId,p.getUniqueId());return x;})).thenAccept(x->main(()->p.sendMessage("[Events] Reward paid: "+reward))).exceptionally(this::failure);}
 private void refund(Player p){async(()->repo.pendingRefunds(p.getUniqueId())).thenAccept(work->main(()->{for(RefundWork refund:work){Material type=Material.valueOf(refund.material());if(space(p,type)<refund.amount()){p.sendMessage("Not enough inventory space; refund remains pending");break;}async(()->repo.reserveRefund(refund.id(),p.getUniqueId())).thenAccept(reserved->main(()->{if(!reserved)return;int left=refund.amount();while(left>0){int chunk=Math.min(left,type.getMaxStackSize());p.getInventory().addItem(new ItemStack(type,chunk));left-=chunk;}async(()->{repo.finishRefund(refund.id(),p.getUniqueId());return null;}).exceptionally(this::failure);})).exceptionally(this::failure);}})).exceptionally(this::failure);}
 private static int space(Player p,Material m){int space=0;for(ItemStack stack:p.getInventory().getStorageContents())space+=stack==null?m.getMaxStackSize():stack.getType()==m?m.getMaxStackSize()-stack.getAmount():0;return space;}
 private static int count(Player p,Material m){return Arrays.stream(p.getInventory().getStorageContents()).filter(Objects::nonNull).filter(i->i.getType()==m).mapToInt(ItemStack::getAmount).sum();}
 private static int remove(Player p,Material m,int amount){int left=amount;for(ItemStack stack:p.getInventory().getStorageContents()){if(stack==null||stack.getType()!=m)continue;int take=Math.min(left,stack.getAmount());stack.subtract(take);left-=take;if(left==0)break;}return amount-left;}
 private <T>CompletableFuture<T> async(Callable<T> task){return CompletableFuture.supplyAsync(()->{try{return task.call();}catch(Exception e){throw new CompletionException(e);}},db);}private void main(Runnable r){Bukkit.getScheduler().runTask(this,r);}private Void failure(Throwable e){getLogger().log(Level.SEVERE,"Event operation failed",e);return null;}public void onDisable(){if(db!=null)db.shutdown();}
}