package com.hardcraft.collections;
import java.nio.file.*;import java.sql.*;import java.util.*;
final class CollectionRepository{
 private final String url;CollectionRepository(Path path){url="jdbc:sqlite:"+path.toAbsolutePath();}
 void migrate(){try{Path p=Path.of(url.substring(12));if(p.getParent()!=null)Files.createDirectories(p.getParent());try(Connection c=open();Statement s=c.createStatement()){s.execute("CREATE TABLE IF NOT EXISTS hardcraft_collection_discoveries(owner_uuid TEXT NOT NULL,category TEXT NOT NULL,entry_id TEXT NOT NULL,discovered_at INTEGER NOT NULL,PRIMARY KEY(owner_uuid,category,entry_id))");s.execute("CREATE TABLE IF NOT EXISTS hardcraft_collection_milestones(owner_uuid TEXT NOT NULL,milestone INTEGER NOT NULL,rewarded_at INTEGER NOT NULL,PRIMARY KEY(owner_uuid,milestone))");}}catch(Exception e){throw new IllegalStateException("Collections migration failed",e);}}
 synchronized boolean discover(UUID owner,String category,String id){valid(category,id);try(Connection c=open();PreparedStatement s=c.prepareStatement("INSERT OR IGNORE INTO hardcraft_collection_discoveries VALUES(?,?,?,?)")){s.setString(1,owner.toString());s.setString(2,category);s.setString(3,id);s.setLong(4,System.currentTimeMillis());return s.executeUpdate()==1;}catch(SQLException e){throw new IllegalStateException("Discovery failed",e);}}
 int count(UUID owner){try(Connection c=open();PreparedStatement s=c.prepareStatement("SELECT COUNT(*) FROM hardcraft_collection_discoveries WHERE owner_uuid=?")){s.setString(1,owner.toString());try(ResultSet r=s.executeQuery()){return r.next()?r.getInt(1):0;}}catch(SQLException e){throw new IllegalStateException("Collection count failed",e);}}
 synchronized boolean claim(UUID owner,int milestone){if(milestone<1)throw new IllegalArgumentException("invalid milestone");try(Connection c=open();PreparedStatement s=c.prepareStatement("INSERT OR IGNORE INTO hardcraft_collection_milestones VALUES(?,?,?)")){s.setString(1,owner.toString());s.setInt(2,milestone);s.setLong(3,System.currentTimeMillis());return s.executeUpdate()==1;}catch(SQLException e){throw new IllegalStateException("Milestone claim failed",e);}}
 private void valid(String category,String id){if(!Set.of("MOB","BIOME","FISH","ARTIFACT").contains(category)||id==null||!id.matches("[a-z0-9_.-]+:[a-z0-9_./-]+"))throw new IllegalArgumentException("invalid canonical collection entry");}
 private Connection open()throws SQLException{Connection c=DriverManager.getConnection(url);try(Statement s=c.createStatement()){s.execute("PRAGMA busy_timeout=5000");}return c;}
}