package com.hardcraft.collections;
import java.nio.file.Path;import java.util.*;import java.util.concurrent.*;import net.kyori.adventure.text.Component;import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.entity.EntityDeathEvent;import org.bukkit.event.player.*;import org.bukkit.plugin.java.JavaPlugin;
public final class HardCraftCollections extends JavaPlugin implements Listener,CommandExecutor{
 private CollectionRepository repo;private ExecutorService db;private Set<String> entries;private List<Integer> milestones;
 public void onEnable(){saveDefaultConfig();entries=Set.copyOf(getConfig().getStringList("entries"));milestones=List.copyOf(getConfig().getIntegerList("milestones"));Path database=Objects.requireNonNull(getServer().getPluginManager().getPlugin("HardCraftCore")).getDataFolder().toPath().resolve("hardcraft.db");repo=new CollectionRepository(database);repo.migrate();db=Executors.newSingleThreadExecutor(Thread.ofPlatform().name("HardCraftCollections-DB").factory());getServer().getPluginManager().registerEvents(this,this);Objects.requireNonNull(getCommand("collections")).setExecutor(this);new StagingProbe(this,repo).run();}
 @EventHandler(ignoreCancelled=true) public void kill(EntityDeathEvent e){Player p=e.getEntity().getKiller();if(p!=null)discover(p,"MOB",e.getEntityType().getKey().toString());}
 @EventHandler(ignoreCancelled=true) public void fish(PlayerFishEvent e){if(e.getState()==PlayerFishEvent.State.CAUGHT_FISH&&e.getCaught() instanceof Item item)discover(e.getPlayer(),"FISH",item.getItemStack().getType().getKey().toString());}
 @EventHandler public void move(PlayerMoveEvent e){if(e.getTo().getBlockX()==e.getFrom().getBlockX()&&e.getTo().getBlockZ()==e.getFrom().getBlockZ())return;discover(e.getPlayer(),"BIOME",e.getTo().getBlock().getBiome().getKey().toString());}
 private void discover(Player p,String category,String id){String entry=category+":"+id;if(!entries.contains(entry))return;CompletableFuture<Boolean> future=CompletableFuture.supplyAsync(()->repo.discover(p.getUniqueId(),category,id),db);future.thenAccept(first->{if(!first)return;int count=repo.count(p.getUniqueId());Bukkit.getScheduler().runTask(this,()->p.sendMessage(Component.text("[Collections] Discovered "+entry+" ("+count+"/"+entries.size()+")")));for(int milestone:milestones)if(count>=milestone&&repo.claim(p.getUniqueId(),milestone))Bukkit.getScheduler().runTask(this,()->p.sendMessage(Component.text("[Collections] Milestone "+milestone+" claimed")));});}
 public boolean onCommand(CommandSender sender,Command command,String label,String[] args){if(!(sender instanceof Player p)){sender.sendMessage(Component.text("Players only"));return true;}CompletableFuture<Integer> future=CompletableFuture.supplyAsync(()->repo.count(p.getUniqueId()),db);future.thenAccept(count->Bukkit.getScheduler().runTask(this,()->p.sendMessage(Component.text("[Collections] "+count+"/"+entries.size()+(getConfig().getBoolean("reveal-missing")?"; entries: "+String.join(", ",entries):"; missing entries hidden")))));return true;}
 public void onDisable(){if(db!=null)db.shutdown();}
}