package com.hardcraft.quests;

import com.hardcraft.core.api.CoreApi;import com.hardcraft.economy.api.EconomyApi;import com.hardcraft.items.api.ItemsApi;import com.hardcraft.profiles.api.ProfilesApi;
import java.nio.file.Path;import java.util.*;import java.util.logging.Level;
import org.bukkit.Material;import org.bukkit.command.*;import org.bukkit.configuration.ConfigurationSection;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.block.BlockBreakEvent;import org.bukkit.event.player.PlayerJoinEvent;import org.bukkit.plugin.java.JavaPlugin;

public final class HardCraftQuests extends JavaPlugin implements Listener,CommandExecutor {
    private CoreApi core;private ProfilesApi profiles;private QuestService quests;private QuestDefinition definition;
    @Override public void onEnable(){try{
        core=Objects.requireNonNull(getServer().getServicesManager().getRegistration(CoreApi.class),"Core API unavailable").getProvider();
        profiles=required(ProfilesApi.class);ItemsApi items=required(ItemsApi.class);EconomyApi economy=required(EconomyApi.class);
        java.io.File questFile=new java.io.File(getDataFolder(),"quests.yml");if(!questFile.exists())saveResource("quests.yml",false);var config=org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(questFile);ConfigurationSection q=Objects.requireNonNull(config.getConfigurationSection("quests.welcome"),"quests.welcome missing");
        String type=q.getString("objective.type");if(!"BREAK".equals(type))throw new IllegalArgumentException("welcome objective.type must be BREAK");String material=Objects.requireNonNull(q.getString("objective.material"),"objective.material missing");Material.valueOf(material);
        definition=new QuestDefinition("welcome",q.getString("title"),material,q.getInt("objective.amount"),q.getLong("rewards.money"),q.getString("rewards.item"),q.getString("next"));if(items.definition(definition.itemId()).isEmpty())throw new IllegalArgumentException("unknown reward item: "+definition.itemId());
        JavaPlugin corePlugin=(JavaPlugin)Objects.requireNonNull(getServer().getPluginManager().getPlugin("HardCraftCore"));Path db=corePlugin.getDataFolder().toPath().resolve("hardcraft.db");QuestRepository repository=new QuestRepository(db);repository.migrate();quests=new QuestService(this,repository,definition,economy,items);
        Objects.requireNonNull(getCommand("quest")).setExecutor(this);Objects.requireNonNull(getCommand("questadmin")).setExecutor(this);getServer().getPluginManager().registerEvents(this,this);getLogger().info("HardCraftQuests v"+getPluginMeta().getVersion()+" enabled; quest=welcome; schema=2");new StagingProbe(this,repository,economy,items,definition).run();
    }catch(RuntimeException e){getLogger().log(Level.SEVERE,"HardCraftQuests failed to start: "+e.getMessage(),e);getServer().getPluginManager().disablePlugin(this);}}
    private <T>T required(Class<T> type){return core.services().find(type).orElseThrow(()->new IllegalStateException(type.getSimpleName()+" unavailable"));}
    @EventHandler public void join(PlayerJoinEvent e){Player p=e.getPlayer();profiles.find(p.getUniqueId()).thenCompose(profile->{if(profile.isEmpty())throw new IllegalStateException("profile unavailable");return quests.resume(p);}).thenAccept(progress->getServer().getScheduler().runTask(this,()->p.sendMessage(quests.describe(progress)))).exceptionally(this::failure);}
    @EventHandler(ignoreCancelled=true,priority=EventPriority.MONITOR) public void broken(BlockBreakEvent e){if(e.getBlock().getType()!=Material.valueOf(definition.material()))return;quests.progress(e.getPlayer().getUniqueId()).thenCompose(p->p!=null&&p.state()==QuestProgress.State.ACTIVE?quests.advance(e.getPlayer()):java.util.concurrent.CompletableFuture.completedFuture(p)).thenAccept(p->{if(p!=null)getServer().getScheduler().runTask(this,()->e.getPlayer().sendMessage(quests.describe(p)));}).exceptionally(this::failure);}
    @Override public boolean onCommand(CommandSender sender,Command command,String label,String[] args){if(command.getName().equals("questadmin")){if(!sender.hasPermission("hardcraft.quests.admin")){sender.sendMessage("No permission");return true;}if(args.length!=2)return false;UUID owner;try{owner=UUID.fromString(args[1]);}catch(IllegalArgumentException e){sender.sendMessage("Invalid UUID");return true;}String actor=sender.getName();var result=switch(args[0].toLowerCase(Locale.ROOT)){case "inspect"->quests.inspect(owner,actor);case "confirm"->quests.resolve(owner,actor,true);case "retry"->quests.resolve(owner,actor,false);default->null;};if(result==null)return false;result.thenAccept(p->sender.sendMessage("Quest audit: "+p)).exceptionally(this::failure);return true;}if(!(sender instanceof Player player)){sender.sendMessage("Players only");return true;}if(!player.hasPermission("hardcraft.quests.use"))return true;String action=args.length==0?"progress":args[0].toLowerCase(Locale.ROOT);if(action.equals("start")){profiles.find(player.getUniqueId()).thenCompose(profile->{if(profile.isEmpty())throw new IllegalStateException("Profile not ready; rejoin and retry");return quests.start(player.getUniqueId());}).thenAccept(p->getServer().getScheduler().runTask(this,()->player.sendMessage(quests.describe(p)))).exceptionally(this::failure);return true;}if(action.equals("progress")){quests.resume(player).thenAccept(p->getServer().getScheduler().runTask(this,()->player.sendMessage(quests.describe(p)))).exceptionally(this::failure);return true;}return false;}
    private Void failure(Throwable e){getLogger().log(Level.SEVERE,"Quest operation failed",e);return null;}
    @Override public void onDisable(){if(quests!=null)quests.close();}
}