package com.hardcraft.quests;

import java.nio.file.*;import java.sql.*;import java.util.*;

final class QuestRepository {
    private final String url;
    QuestRepository(Path database){url="jdbc:sqlite:"+database.toAbsolutePath();}
    void migrate(){try{Path p=Path.of(url.substring(12));if(p.getParent()!=null)Files.createDirectories(p.getParent());try(Connection c=open();Statement s=c.createStatement()){s.execute("BEGIN IMMEDIATE");try{s.execute("CREATE TABLE IF NOT EXISTS hardcraft_quests_schema_version(version INTEGER PRIMARY KEY,applied_at TEXT NOT NULL)");String old=null;try(ResultSet r=s.executeQuery("SELECT sql FROM sqlite_master WHERE type='table' AND name='hardcraft_quest_progress'")){if(r.next())old=r.getString(1);}if(old!=null&&!old.contains("REVIEW_REQUIRED")){s.execute("ALTER TABLE hardcraft_quest_progress RENAME TO hardcraft_quest_progress_v1");}s.execute("CREATE TABLE IF NOT EXISTS hardcraft_quest_progress(owner_uuid TEXT NOT NULL,quest_id TEXT NOT NULL,progress INTEGER NOT NULL CHECK(progress>=0),state TEXT NOT NULL CHECK(state IN ('ACTIVE','REWARDING','REVIEW_REQUIRED','COMPLETED')),money_paid INTEGER NOT NULL DEFAULT 0 CHECK(money_paid IN (0,1)),item_delivered INTEGER NOT NULL DEFAULT 0 CHECK(item_delivered IN (0,1)),updated_at INTEGER NOT NULL,PRIMARY KEY(owner_uuid,quest_id))");if(old!=null&&!old.contains("REVIEW_REQUIRED")){s.execute("INSERT INTO hardcraft_quest_progress SELECT * FROM hardcraft_quest_progress_v1");s.execute("DROP TABLE hardcraft_quest_progress_v1");}s.execute("CREATE TABLE IF NOT EXISTS hardcraft_quest_audit(id INTEGER PRIMARY KEY AUTOINCREMENT,occurred_at INTEGER NOT NULL,actor TEXT NOT NULL,owner_uuid TEXT NOT NULL,quest_id TEXT NOT NULL,action TEXT NOT NULL,detail TEXT NOT NULL)");s.executeUpdate("INSERT OR IGNORE INTO hardcraft_quests_schema_version VALUES(2,CURRENT_TIMESTAMP)");s.execute("COMMIT");}catch(Exception e){s.execute("ROLLBACK");throw e;}}}catch(Exception e){throw fail("migration",e);}}
    long auditCount(UUID owner,String id){try(Connection c=open();PreparedStatement s=c.prepareStatement("SELECT COUNT(*) FROM hardcraft_quest_audit WHERE owner_uuid=? AND quest_id=?")){s.setString(1,owner.toString());s.setString(2,id);try(ResultSet r=s.executeQuery()){return r.getLong(1);}}catch(SQLException e){throw fail("audit count",e);}}
    QuestProgress start(UUID owner,String id){Objects.requireNonNull(owner);try(Connection c=open();PreparedStatement s=c.prepareStatement("INSERT OR IGNORE INTO hardcraft_quest_progress VALUES(?,?,0,'ACTIVE',0,0,?)")){s.setString(1,owner.toString());s.setString(2,id);s.setLong(3,System.currentTimeMillis());s.executeUpdate();return find(owner,id).orElseThrow();}catch(SQLException e){throw fail("start",e);}}
    Optional<QuestProgress> find(UUID owner,String id){try(Connection c=open();PreparedStatement s=c.prepareStatement("SELECT progress,state,money_paid,item_delivered FROM hardcraft_quest_progress WHERE owner_uuid=? AND quest_id=?")){s.setString(1,owner.toString());s.setString(2,id);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(row(owner,id,r)):Optional.empty();}}catch(SQLException e){throw fail("lookup",e);}}
    QuestProgress advance(UUID owner,String id,int target){try(Connection c=open();PreparedStatement s=c.prepareStatement("UPDATE hardcraft_quest_progress SET progress=MIN(progress+1,?),state=CASE WHEN progress+1>=? THEN 'REWARDING' ELSE state END,updated_at=? WHERE owner_uuid=? AND quest_id=? AND state='ACTIVE'")){s.setInt(1,target);s.setInt(2,target);s.setLong(3,System.currentTimeMillis());s.setString(4,owner.toString());s.setString(5,id);s.executeUpdate();return find(owner,id).orElseThrow();}catch(SQLException e){throw fail("advance",e);}}
    QuestProgress markMoney(UUID owner,String id){return flag(owner,id,"money_paid");}
    QuestProgress markItem(UUID owner,String id){return flag(owner,id,"item_delivered");}
    QuestProgress requireReview(UUID owner,String id,String actor,String detail){return state(owner,id,"REVIEW_REQUIRED",actor,"ITEM_MISMATCH",detail);}
    QuestProgress resolve(UUID owner,String id,String actor,boolean confirm){return state(owner,id,confirm?"COMPLETED":"REWARDING",actor,confirm?"ADMIN_CONFIRM_ITEM":"ADMIN_ALLOW_RETRY",confirm?"existing reward confirmed":"retry authorized");}
    void audit(UUID owner,String id,String actor,String action,String detail){try(Connection c=open();PreparedStatement s=c.prepareStatement("INSERT INTO hardcraft_quest_audit(occurred_at,actor,owner_uuid,quest_id,action,detail) VALUES(?,?,?,?,?,?)")){s.setLong(1,System.currentTimeMillis());s.setString(2,actor);s.setString(3,owner.toString());s.setString(4,id);s.setString(5,action);s.setString(6,detail);s.executeUpdate();}catch(SQLException e){throw fail("audit",e);}}
    private QuestProgress state(UUID owner,String id,String state,String actor,String action,String detail){try(Connection c=open()){c.setAutoCommit(false);try(PreparedStatement u=c.prepareStatement("UPDATE hardcraft_quest_progress SET state=?,item_delivered=CASE WHEN ?='COMPLETED' THEN 1 ELSE item_delivered END,updated_at=? WHERE owner_uuid=? AND quest_id=?");PreparedStatement a=c.prepareStatement("INSERT INTO hardcraft_quest_audit(occurred_at,actor,owner_uuid,quest_id,action,detail) VALUES(?,?,?,?,?,?)")){long now=System.currentTimeMillis();u.setString(1,state);u.setString(2,state);u.setLong(3,now);u.setString(4,owner.toString());u.setString(5,id);if(u.executeUpdate()!=1)throw new IllegalArgumentException("quest progress not found");a.setLong(1,now);a.setString(2,actor);a.setString(3,owner.toString());a.setString(4,id);a.setString(5,action);a.setString(6,detail);a.executeUpdate();c.commit();}catch(Exception e){c.rollback();throw e;}return find(owner,id).orElseThrow();}catch(Exception e){throw fail("state update",e);}}
    private QuestProgress flag(UUID owner,String id,String column){try(Connection c=open();PreparedStatement s=c.prepareStatement("UPDATE hardcraft_quest_progress SET "+column+"=1,state=CASE WHEN "+(column.equals("money_paid")?"item_delivered":"money_paid")+"=1 THEN 'COMPLETED' ELSE state END,updated_at=? WHERE owner_uuid=? AND quest_id=? AND state IN ('REWARDING','COMPLETED')")){s.setLong(1,System.currentTimeMillis());s.setString(2,owner.toString());s.setString(3,id);s.executeUpdate();return find(owner,id).orElseThrow();}catch(SQLException e){throw fail("reward update",e);}}
    private Connection open()throws SQLException{Connection c=DriverManager.getConnection(url);try(Statement s=c.createStatement()){s.execute("PRAGMA busy_timeout=15000");}return c;}
    private static QuestProgress row(UUID owner,String id,ResultSet r)throws SQLException{return new QuestProgress(owner,id,r.getInt(1),QuestProgress.State.valueOf(r.getString(2)),r.getInt(3)!=0,r.getInt(4)!=0);}
    private static IllegalStateException fail(String op,Exception e){return new IllegalStateException("Quest "+op+" failed: "+e.getMessage(),e);}
}